// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatservice.proto

#ifndef PROTOBUF_chatservice_2eproto__INCLUDED
#define PROTOBUF_chatservice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace chatserver {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_chatservice_2eproto();
void protobuf_AssignDesc_chatservice_2eproto();
void protobuf_ShutdownFile_chatservice_2eproto();

class ChatMsg;
class Commands;
class JoinRequest;
class Stats;
class User;
class timeline;

enum Stats_MsgType {
  Stats_MsgType_CHAT = 0,
  Stats_MsgType_COMMAND = 1,
  Stats_MsgType_Stats_MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Stats_MsgType_Stats_MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Stats_MsgType_IsValid(int value);
const Stats_MsgType Stats_MsgType_MsgType_MIN = Stats_MsgType_CHAT;
const Stats_MsgType Stats_MsgType_MsgType_MAX = Stats_MsgType_COMMAND;
const int Stats_MsgType_MsgType_ARRAYSIZE = Stats_MsgType_MsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Stats_MsgType_descriptor();
inline const ::std::string& Stats_MsgType_Name(Stats_MsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Stats_MsgType_descriptor(), value);
}
inline bool Stats_MsgType_Parse(
    const ::std::string& name, Stats_MsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Stats_MsgType>(
    Stats_MsgType_descriptor(), name, value);
}
enum Commands_type {
  Commands_type_List = 0,
  Commands_type_Join = 1,
  Commands_type_Leave = 2,
  Commands_type_Chat = 3,
  Commands_type_Commands_type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Commands_type_Commands_type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Commands_type_IsValid(int value);
const Commands_type Commands_type_type_MIN = Commands_type_List;
const Commands_type Commands_type_type_MAX = Commands_type_Chat;
const int Commands_type_type_ARRAYSIZE = Commands_type_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Commands_type_descriptor();
inline const ::std::string& Commands_type_Name(Commands_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Commands_type_descriptor(), value);
}
inline bool Commands_type_Parse(
    const ::std::string& name, Commands_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Commands_type>(
    Commands_type_descriptor(), name, value);
}
// ===================================================================

class Stats : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:chatserver.Stats) */ {
 public:
  Stats();
  virtual ~Stats();

  Stats(const Stats& from);

  inline Stats& operator=(const Stats& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stats& default_instance();

  void Swap(Stats* other);

  // implements Message ----------------------------------------------

  inline Stats* New() const { return New(NULL); }

  Stats* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stats& from);
  void MergeFrom(const Stats& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Stats* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Stats_MsgType MsgType;
  static const MsgType CHAT =
    Stats_MsgType_CHAT;
  static const MsgType COMMAND =
    Stats_MsgType_COMMAND;
  static inline bool MsgType_IsValid(int value) {
    return Stats_MsgType_IsValid(value);
  }
  static const MsgType MsgType_MIN =
    Stats_MsgType_MsgType_MIN;
  static const MsgType MsgType_MAX =
    Stats_MsgType_MsgType_MAX;
  static const int MsgType_ARRAYSIZE =
    Stats_MsgType_MsgType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MsgType_descriptor() {
    return Stats_MsgType_descriptor();
  }
  static inline const ::std::string& MsgType_Name(MsgType value) {
    return Stats_MsgType_Name(value);
  }
  static inline bool MsgType_Parse(const ::std::string& name,
      MsgType* value) {
    return Stats_MsgType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:chatserver.Stats)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chatservice_2eproto();
  friend void protobuf_AssignDesc_chatservice_2eproto();
  friend void protobuf_ShutdownFile_chatservice_2eproto();

  void InitAsDefaultInstance();
  static Stats* default_instance_;
};
// -------------------------------------------------------------------

class timeline : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:chatserver.timeline) */ {
 public:
  timeline();
  virtual ~timeline();

  timeline(const timeline& from);

  inline timeline& operator=(const timeline& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const timeline& default_instance();

  void Swap(timeline* other);

  // implements Message ----------------------------------------------

  inline timeline* New() const { return New(NULL); }

  timeline* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const timeline& from);
  void MergeFrom(const timeline& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(timeline* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .chatserver.Stats statuses = 1;
  int statuses_size() const;
  void clear_statuses();
  static const int kStatusesFieldNumber = 1;
  const ::chatserver::Stats& statuses(int index) const;
  ::chatserver::Stats* mutable_statuses(int index);
  ::chatserver::Stats* add_statuses();
  ::google::protobuf::RepeatedPtrField< ::chatserver::Stats >*
      mutable_statuses();
  const ::google::protobuf::RepeatedPtrField< ::chatserver::Stats >&
      statuses() const;

  // @@protoc_insertion_point(class_scope:chatserver.timeline)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::chatserver::Stats > statuses_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chatservice_2eproto();
  friend void protobuf_AssignDesc_chatservice_2eproto();
  friend void protobuf_ShutdownFile_chatservice_2eproto();

  void InitAsDefaultInstance();
  static timeline* default_instance_;
};
// -------------------------------------------------------------------

class ChatMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:chatserver.ChatMsg) */ {
 public:
  ChatMsg();
  virtual ~ChatMsg();

  ChatMsg(const ChatMsg& from);

  inline ChatMsg& operator=(const ChatMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMsg& default_instance();

  void Swap(ChatMsg* other);

  // implements Message ----------------------------------------------

  inline ChatMsg* New() const { return New(NULL); }

  ChatMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMsg& from);
  void MergeFrom(const ChatMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChatMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // optional int64 timeStamp = 3;
  void clear_timestamp();
  static const int kTimeStampFieldNumber = 3;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:chatserver.ChatMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int64 timestamp_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chatservice_2eproto();
  friend void protobuf_AssignDesc_chatservice_2eproto();
  friend void protobuf_ShutdownFile_chatservice_2eproto();

  void InitAsDefaultInstance();
  static ChatMsg* default_instance_;
};
// -------------------------------------------------------------------

class Commands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:chatserver.Commands) */ {
 public:
  Commands();
  virtual ~Commands();

  Commands(const Commands& from);

  inline Commands& operator=(const Commands& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Commands& default_instance();

  void Swap(Commands* other);

  // implements Message ----------------------------------------------

  inline Commands* New() const { return New(NULL); }

  Commands* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Commands& from);
  void MergeFrom(const Commands& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Commands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Commands_type type;
  static const type List =
    Commands_type_List;
  static const type Join =
    Commands_type_Join;
  static const type Leave =
    Commands_type_Leave;
  static const type Chat =
    Commands_type_Chat;
  static inline bool type_IsValid(int value) {
    return Commands_type_IsValid(value);
  }
  static const type type_MIN =
    Commands_type_type_MIN;
  static const type type_MAX =
    Commands_type_type_MAX;
  static const int type_ARRAYSIZE =
    Commands_type_type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  type_descriptor() {
    return Commands_type_descriptor();
  }
  static inline const ::std::string& type_Name(type value) {
    return Commands_type_Name(value);
  }
  static inline bool type_Parse(const ::std::string& name,
      type* value) {
    return Commands_type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional int32 commandType = 1;
  void clear_commandtype();
  static const int kCommandTypeFieldNumber = 1;
  ::google::protobuf::int32 commandtype() const;
  void set_commandtype(::google::protobuf::int32 value);

  // optional string roomName = 2;
  void clear_roomname();
  static const int kRoomNameFieldNumber = 2;
  const ::std::string& roomname() const;
  void set_roomname(const ::std::string& value);
  void set_roomname(const char* value);
  void set_roomname(const char* value, size_t size);
  ::std::string* mutable_roomname();
  ::std::string* release_roomname();
  void set_allocated_roomname(::std::string* roomname);

  // @@protoc_insertion_point(class_scope:chatserver.Commands)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr roomname_;
  ::google::protobuf::int32 commandtype_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chatservice_2eproto();
  friend void protobuf_AssignDesc_chatservice_2eproto();
  friend void protobuf_ShutdownFile_chatservice_2eproto();

  void InitAsDefaultInstance();
  static Commands* default_instance_;
};
// -------------------------------------------------------------------

class User : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:chatserver.User) */ {
 public:
  User();
  virtual ~User();

  User(const User& from);

  inline User& operator=(const User& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const User& default_instance();

  void Swap(User* other);

  // implements Message ----------------------------------------------

  inline User* New() const { return New(NULL); }

  User* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const User& from);
  void MergeFrom(const User& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(User* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // repeated .chatserver.ChatMsg log = 2;
  int log_size() const;
  void clear_log();
  static const int kLogFieldNumber = 2;
  const ::chatserver::ChatMsg& log(int index) const;
  ::chatserver::ChatMsg* mutable_log(int index);
  ::chatserver::ChatMsg* add_log();
  ::google::protobuf::RepeatedPtrField< ::chatserver::ChatMsg >*
      mutable_log();
  const ::google::protobuf::RepeatedPtrField< ::chatserver::ChatMsg >&
      log() const;

  // repeated .chatserver.User subscription = 3;
  int subscription_size() const;
  void clear_subscription();
  static const int kSubscriptionFieldNumber = 3;
  const ::chatserver::User& subscription(int index) const;
  ::chatserver::User* mutable_subscription(int index);
  ::chatserver::User* add_subscription();
  ::google::protobuf::RepeatedPtrField< ::chatserver::User >*
      mutable_subscription();
  const ::google::protobuf::RepeatedPtrField< ::chatserver::User >&
      subscription() const;

  // @@protoc_insertion_point(class_scope:chatserver.User)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::RepeatedPtrField< ::chatserver::ChatMsg > log_;
  ::google::protobuf::RepeatedPtrField< ::chatserver::User > subscription_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chatservice_2eproto();
  friend void protobuf_AssignDesc_chatservice_2eproto();
  friend void protobuf_ShutdownFile_chatservice_2eproto();

  void InitAsDefaultInstance();
  static User* default_instance_;
};
// -------------------------------------------------------------------

class JoinRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:chatserver.JoinRequest) */ {
 public:
  JoinRequest();
  virtual ~JoinRequest();

  JoinRequest(const JoinRequest& from);

  inline JoinRequest& operator=(const JoinRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JoinRequest& default_instance();

  void Swap(JoinRequest* other);

  // implements Message ----------------------------------------------

  inline JoinRequest* New() const { return New(NULL); }

  JoinRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JoinRequest& from);
  void MergeFrom(const JoinRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JoinRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:chatserver.JoinRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_chatservice_2eproto();
  friend void protobuf_AssignDesc_chatservice_2eproto();
  friend void protobuf_ShutdownFile_chatservice_2eproto();

  void InitAsDefaultInstance();
  static JoinRequest* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Stats

// optional string name = 1;
inline void Stats::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Stats::name() const {
  // @@protoc_insertion_point(field_get:chatserver.Stats.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Stats::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chatserver.Stats.name)
}
inline void Stats::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chatserver.Stats.name)
}
inline void Stats::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chatserver.Stats.name)
}
inline ::std::string* Stats::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:chatserver.Stats.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Stats::release_name() {
  // @@protoc_insertion_point(field_release:chatserver.Stats.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Stats::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:chatserver.Stats.name)
}

// optional string msg = 2;
inline void Stats::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Stats::msg() const {
  // @@protoc_insertion_point(field_get:chatserver.Stats.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Stats::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chatserver.Stats.msg)
}
inline void Stats::set_msg(const char* value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chatserver.Stats.msg)
}
inline void Stats::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chatserver.Stats.msg)
}
inline ::std::string* Stats::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:chatserver.Stats.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Stats::release_msg() {
  // @@protoc_insertion_point(field_release:chatserver.Stats.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Stats::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:chatserver.Stats.msg)
}

// -------------------------------------------------------------------

// timeline

// repeated .chatserver.Stats statuses = 1;
inline int timeline::statuses_size() const {
  return statuses_.size();
}
inline void timeline::clear_statuses() {
  statuses_.Clear();
}
inline const ::chatserver::Stats& timeline::statuses(int index) const {
  // @@protoc_insertion_point(field_get:chatserver.timeline.statuses)
  return statuses_.Get(index);
}
inline ::chatserver::Stats* timeline::mutable_statuses(int index) {
  // @@protoc_insertion_point(field_mutable:chatserver.timeline.statuses)
  return statuses_.Mutable(index);
}
inline ::chatserver::Stats* timeline::add_statuses() {
  // @@protoc_insertion_point(field_add:chatserver.timeline.statuses)
  return statuses_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::chatserver::Stats >*
timeline::mutable_statuses() {
  // @@protoc_insertion_point(field_mutable_list:chatserver.timeline.statuses)
  return &statuses_;
}
inline const ::google::protobuf::RepeatedPtrField< ::chatserver::Stats >&
timeline::statuses() const {
  // @@protoc_insertion_point(field_list:chatserver.timeline.statuses)
  return statuses_;
}

// -------------------------------------------------------------------

// ChatMsg

// optional string name = 1;
inline void ChatMsg::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChatMsg::name() const {
  // @@protoc_insertion_point(field_get:chatserver.ChatMsg.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMsg::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chatserver.ChatMsg.name)
}
inline void ChatMsg::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chatserver.ChatMsg.name)
}
inline void ChatMsg::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chatserver.ChatMsg.name)
}
inline ::std::string* ChatMsg::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:chatserver.ChatMsg.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatMsg::release_name() {
  // @@protoc_insertion_point(field_release:chatserver.ChatMsg.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMsg::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:chatserver.ChatMsg.name)
}

// optional string msg = 2;
inline void ChatMsg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChatMsg::msg() const {
  // @@protoc_insertion_point(field_get:chatserver.ChatMsg.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMsg::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chatserver.ChatMsg.msg)
}
inline void ChatMsg::set_msg(const char* value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chatserver.ChatMsg.msg)
}
inline void ChatMsg::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chatserver.ChatMsg.msg)
}
inline ::std::string* ChatMsg::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:chatserver.ChatMsg.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatMsg::release_msg() {
  // @@protoc_insertion_point(field_release:chatserver.ChatMsg.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMsg::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:chatserver.ChatMsg.msg)
}

// optional int64 timeStamp = 3;
inline void ChatMsg::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ChatMsg::timestamp() const {
  // @@protoc_insertion_point(field_get:chatserver.ChatMsg.timeStamp)
  return timestamp_;
}
inline void ChatMsg::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:chatserver.ChatMsg.timeStamp)
}

// -------------------------------------------------------------------

// Commands

// optional int32 commandType = 1;
inline void Commands::clear_commandtype() {
  commandtype_ = 0;
}
inline ::google::protobuf::int32 Commands::commandtype() const {
  // @@protoc_insertion_point(field_get:chatserver.Commands.commandType)
  return commandtype_;
}
inline void Commands::set_commandtype(::google::protobuf::int32 value) {
  
  commandtype_ = value;
  // @@protoc_insertion_point(field_set:chatserver.Commands.commandType)
}

// optional string roomName = 2;
inline void Commands::clear_roomname() {
  roomname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Commands::roomname() const {
  // @@protoc_insertion_point(field_get:chatserver.Commands.roomName)
  return roomname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Commands::set_roomname(const ::std::string& value) {
  
  roomname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chatserver.Commands.roomName)
}
inline void Commands::set_roomname(const char* value) {
  
  roomname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chatserver.Commands.roomName)
}
inline void Commands::set_roomname(const char* value, size_t size) {
  
  roomname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chatserver.Commands.roomName)
}
inline ::std::string* Commands::mutable_roomname() {
  
  // @@protoc_insertion_point(field_mutable:chatserver.Commands.roomName)
  return roomname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Commands::release_roomname() {
  // @@protoc_insertion_point(field_release:chatserver.Commands.roomName)
  
  return roomname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Commands::set_allocated_roomname(::std::string* roomname) {
  if (roomname != NULL) {
    
  } else {
    
  }
  roomname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), roomname);
  // @@protoc_insertion_point(field_set_allocated:chatserver.Commands.roomName)
}

// -------------------------------------------------------------------

// User

// optional string name = 1;
inline void User::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& User::name() const {
  // @@protoc_insertion_point(field_get:chatserver.User.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void User::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chatserver.User.name)
}
inline void User::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chatserver.User.name)
}
inline void User::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chatserver.User.name)
}
inline ::std::string* User::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:chatserver.User.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* User::release_name() {
  // @@protoc_insertion_point(field_release:chatserver.User.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void User::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:chatserver.User.name)
}

// repeated .chatserver.ChatMsg log = 2;
inline int User::log_size() const {
  return log_.size();
}
inline void User::clear_log() {
  log_.Clear();
}
inline const ::chatserver::ChatMsg& User::log(int index) const {
  // @@protoc_insertion_point(field_get:chatserver.User.log)
  return log_.Get(index);
}
inline ::chatserver::ChatMsg* User::mutable_log(int index) {
  // @@protoc_insertion_point(field_mutable:chatserver.User.log)
  return log_.Mutable(index);
}
inline ::chatserver::ChatMsg* User::add_log() {
  // @@protoc_insertion_point(field_add:chatserver.User.log)
  return log_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::chatserver::ChatMsg >*
User::mutable_log() {
  // @@protoc_insertion_point(field_mutable_list:chatserver.User.log)
  return &log_;
}
inline const ::google::protobuf::RepeatedPtrField< ::chatserver::ChatMsg >&
User::log() const {
  // @@protoc_insertion_point(field_list:chatserver.User.log)
  return log_;
}

// repeated .chatserver.User subscription = 3;
inline int User::subscription_size() const {
  return subscription_.size();
}
inline void User::clear_subscription() {
  subscription_.Clear();
}
inline const ::chatserver::User& User::subscription(int index) const {
  // @@protoc_insertion_point(field_get:chatserver.User.subscription)
  return subscription_.Get(index);
}
inline ::chatserver::User* User::mutable_subscription(int index) {
  // @@protoc_insertion_point(field_mutable:chatserver.User.subscription)
  return subscription_.Mutable(index);
}
inline ::chatserver::User* User::add_subscription() {
  // @@protoc_insertion_point(field_add:chatserver.User.subscription)
  return subscription_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::chatserver::User >*
User::mutable_subscription() {
  // @@protoc_insertion_point(field_mutable_list:chatserver.User.subscription)
  return &subscription_;
}
inline const ::google::protobuf::RepeatedPtrField< ::chatserver::User >&
User::subscription() const {
  // @@protoc_insertion_point(field_list:chatserver.User.subscription)
  return subscription_;
}

// -------------------------------------------------------------------

// JoinRequest

// optional string name = 1;
inline void JoinRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JoinRequest::name() const {
  // @@protoc_insertion_point(field_get:chatserver.JoinRequest.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JoinRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:chatserver.JoinRequest.name)
}
inline void JoinRequest::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chatserver.JoinRequest.name)
}
inline void JoinRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chatserver.JoinRequest.name)
}
inline ::std::string* JoinRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:chatserver.JoinRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JoinRequest::release_name() {
  // @@protoc_insertion_point(field_release:chatserver.JoinRequest.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JoinRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:chatserver.JoinRequest.name)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace chatserver

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::chatserver::Stats_MsgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chatserver::Stats_MsgType>() {
  return ::chatserver::Stats_MsgType_descriptor();
}
template <> struct is_proto_enum< ::chatserver::Commands_type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chatserver::Commands_type>() {
  return ::chatserver::Commands_type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_chatservice_2eproto__INCLUDED
